### PR TITLE
skip non-functional stream urls

### PR DESCRIPTION
**Pull request by alexhartl**
Many stations on Dirble offer multiple streams. From these streams often some a non-functional (a prominent example is BBC Radio 1, 2, ...).

This patch checks the provided uri first using the HTTP HEAD method (saving bandwidth) or a usual HTTP request if this doesn't work.

### CODE REVIEW

**Comment by adamcik** [comment]
I see the travis builds are failing because we depend on a unreleased mopidy version. I need to get that fixed, or just get the 1.1 release out :-)

What about non-http streams like mms etc? I know @kingosticks was trying to solve something similar for mopidy-tunein and was using our scanner API to check so that we can verify anything GStreamer can handle.

Haven't looked at the code in any detail as I don't have time just now, but I hope to get to it some time next week.

**Comment by kingosticks** [comment]
What I currently have implemented with the scanner is pretty bad. Streams will often fail the scan (for all kinds of reasons) but then actually play just fine. 

But I was going to comment here that a solution for this problem belongs in Mopidy, not individual extensions. i.e. I want to use it too!

**Comment by alexhartl** [comment]
Non-http streams are quite difficult to check, especially as you don't want to introduce a large delay.

For implementing this in Mopidy directly I think there are 2 possibilities: either allow backends to provide multiple uris for each track or provide a callback like 'I can't play that track. Are you sure it's the right uri?' The question is if this funcionality is universal enough to go into Mopidy itself.

I would at least merge lines 167-170 of my file because they already provide a way better experience.

**Comment by adamcik** [comment]
Looking at the dirble API output it provides a status field we can filter on. I.e. dirble already does this checking for us. So I'm switching to using that instead of this change.

In the future I might look into making something similar to the metadata scanner in mopidy, but oriented towards checking stream health, not fetching metadata. This would be integrated into the stream backend and should if done right fix this once and for all across extensions.

Thanks for looking into this and doing the leg work even if we aren't going to merge this. And if my status fix isn't enough then I will definitely revisit your approach.

**Comment by kingosticks** [comment]
Unless I'm missing something, filtering/sorting  status field is part of this fix!

**Comment by adamcik** [comment]
Very true, and also the part that was pointed out that I should keep if taking an alternate route. Think I've been at it a bit to long today if this is what my reading skills have come to.

**Pull request closed without merging**
